project:
  output-dir: _output

toc: true
number-sections: true
lang: en

format:
  html:
    code-fold: true
  pdf: default
  ipynb: default

jupyter: python3

execute:
  eval: true
  freeze: true
  cache: true