---
title: "Wijklabels"
author: "Balázs Dukai, Ravi Peters"
date: last-modified
---
```{python}
import pandas as pd
```


# Introduction

challanges:
- the position of a VBO is not known in a pand

# Preparing the input

## BAG and 3DBAG

We used the [3DBAG](https://3dbag.nl) version `2023.10.08`.
We used the party walls data that were computed from the same 3DBAG version and delivered as a CSV file to the RVO (`3dbag_v20231008_rvo_export.csv`).

The 3DBAG `2023.10.08` is based on the BAG 2.0 Extract of 08.09.2023.

Only those VBO-s are selected whose usage (gebruiksdoel) includes woonfunctie.

## Number of floors {#sec-floors}

Required for distributing the VBO-s in the Pand.
We compute the number of floors by dividing the gebruiksoppervlakte by the area of the roofprint taken from the 3DBAG.
The gebruiksoppervlakte is the sum of each VBO's `oppervlakte` in the BAG.
The roofprint area is the [totale oppervlakte begane grond](https://docs.3dbag.nl/nl/schema/attributes/#b3_opp_grond), without any underground parts.
The resulting value is rounded up to the nearest whole number, which gives us the number of floors.

::: {.callout-note title="Assumption"}
We can reliably estimate the number of floors in a Pand only from its roofprint area and the area of its VBO-s.
:::

```{sql-postgresql}
CREATE TABLE wijklabels.floors AS
WITH gb AS (SELECT pand_identificatie
                 , sum(oppervlakte) AS gebruiksoppervlakte
                 , count(*)         AS vbo_count
            FROM wijklabels.pand_vbo_woonfunctie
            GROUP BY pand_identificatie)
SELECT gb.pand_identificatie
     , ceil(gb.gebruiksoppervlakte / pw.b3_opp_grond)::int4 AS nr_floors
     , gb.vbo_count
FROM public.party_walls AS pw
         JOIN gb ON pw.identificatie = gb.pand_identificatie
WHERE pw.b3_opp_grond > 0.0;

COMMENT ON TABLE wijklabels.floors IS 'The estimated number of floors per pand.';
```

## Dwelling types

Dwellings are classified into distinct types.
The current classification, as used by the NTA8800 method, is listed below.
In case of appartements, hoek/tussen refers to the horizontal position of the appartement in the building, while vloer/midden/dak/dakvloer refers to its vertical position.
For the sake of simplicity, we refer to this classification as **NTA8800-types**.

Eengezinswoningen:

- vrijstaande woning
- 2 onder 1 kap
- rijwoning tussen
- rijwoning hoek

Meergezinswoningen:

- appartement - hoekvloer
- appartement - hoekmidden
- appartement - hoekdak
- appartement - hoekdakvloer
- appartement - tussenvloer
- appartement - tussenmidden
- appartement - tussendak
- appartement - tussendakvloer

Before the introduction of the NTA8800 method, dwellings were classified slightly differently.
This is the classification used by the WoON2022 study.
For the sake of simplicity, we refer to this classification as **pre-NTA8800-types**.

Eengezinswoningen:

- vrijstaande woning
- 2 onder 1 kap
- rijwoning tussen
- rijwoning hoek

Meergezinswoningen:

- maisonette
- galerij
- portiek
- flat (overig)

The types of the single family houses are equivalent before and after NTA8800.
On the other hand, there is no relation between the types of the meergezingswoningen before and after NTA8800.

This work requires that we know both the *NTA8800* and the *pre-NTA8800* type of each dwelling.
The *pre-NTA8800* type is needed, because that is used by the WoON2022 study, and the *NTA8800* type is needed, because that is used by the validation data on EP-Online.

We first estimate the *NTA8800* type and then convert that to a *pre-NTA8800* type.
The method for classifying the een- and meergezinswoningen differs significantly.

### Classification of a Pand

Each BAG Pand are classified by clustering the intersecting BAG geometries.
For example, a row of five row-houses forms one cluster, because they form a group of connected objects.
We determine the types *vrijstaand/2 onder 1 kap/rijwoning* from the number of buildings in the cluster.
In case of a *rijwoning*, we determine its position *hoek/tussen* from the number intersections with other buildings in the cluster.

Misclassification occurs if the intersections are incorrectly determined, usually, because there is a small gap between BAG polygons that are supposed to be touching. 
Thus, in order to improve the classification of eengezinswoningen, the BAG polygons need topological correction so the gaps and overlaps are corrected.

### Eengezinswoningen

If a pand only contains a single VBO, then we consider the VBO an *eengezinswoning* and the VBO receives the classification of the pand.

### Meergezinswoningen

The meergezingswoningen consist of a single main type, *appartement*.
If a pand contains more than one VBO, then all of its VBOs are classified as *appartement*.

The *appartement* subtypes are determined from the vertical and horizonal position of the VBO within the pand.
Firstly, the VBO-s are distributed across the floors (see @sec-floors) of the pand to determine their vertical position.
Each floor is assigned the same number of appartements, which is calculated by dividing the number of VBO-s by the number of floors.
We call the *number of appartements per floor* `N`.
Then the total appartements in the pand are distributed so that the first `N` is assigned to the ground floor (*vloer*), the second `N` is assigned to the top floor (*dak*) and the rest is distributed evenly across the floors in between (*midden*).
If a pand has the same *number of appartements per floor* as the total number of appartements, then the appartements are classified as *dakvloer*.

Secondly, the appartements are distributed horizontally on each floor.
We assume two configurations for the layout of the appartements, single row or double row.
The choice between single or double row depends on the number of appartements per floor and a random choice.
If the number of appartements per floor is less than or equal three, then a single row layout is chosen, otherwise there is a 50% chance for a double row layout.
Additionally, the number of *hoek* appartements are estimated based on the classification of the pand and the previously determined layout.
If there are remaining appartements on the floor that are not classified as *hoek*, they are classified as *tussen*.

**compare to the ep-online nta8800 woningtype**

## Construction year

The WoON2022 study determines at most seven construction year periods, depending on the dwelling type.
We used the *energy label distributions data* as a reference for the periods.

```{python}
df = pd.read_csv('/home/balazs/Development/wijklabels/tests/data/output/labels_individual.csv', usecols=["bouwperiode", "woningtype", "woningtype_pre_nta8800"])
pd.pivot_table(df, index=["bouwperiode"], columns=["woningtype_pre_nta8800"],
                    aggfunc="count", fill_value="")
```


## Neighborhoods

The neighborhood boundaries are retrieved from CBS.

Version: 2022 v1, [link to data](https://service.pdok.nl/cbs/wijkenbuurten/2022/atom/downloads/wijkenbuurten_2022_v1.gpkg)


required inputs:

- ~~number of floors~~
- dwelling types:
  - types of single-vbo houses
  - types of apartements
- ~~mapping between the pre-nta and nta types~~
- ~~construction year~~
- form factor
- energy label distributions
- ~~neighborhoods~~

# Estimating the energy labels

# Results

**number of vbo did not get label because distribution**