services:
  baseregisters:
    image: "postgis/postgis:15-3.4-alpine"
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - "../tests/data/input_postgres/create_bag_pand_table.sql.gz:/docker-entrypoint-initdb.d/create_bag_pand_table.sql.gz"
      - "../tests/data/input_postgres/create_bag_nummeraanduiding_table.sql.gz:/docker-entrypoint-initdb.d/create_bag_nummeraanduiding_table.sql.gz"
      - "../tests/data/input_postgres/create_bag_verblijfsobject_table.sql.gz:/docker-entrypoint-initdb.d/create_bag_verblijfsobject_table.sql.gz"
      - "../tests/data/input_postgres/insert_bag_pand.sql.gz:/docker-entrypoint-initdb.d/insert_bag_pand.sql.gz"
      - "../tests/data/input_postgres/insert_bag_nummeraanduiding.sql.gz:/docker-entrypoint-initdb.d/insert_bag_nummeraanduiding.sql.gz"
      - "../tests/data/input_postgres/insert_bag_verblijfsobject.sql.gz:/docker-entrypoint-initdb.d/insert_bag_verblijfsobject.sql.gz"
      - "../tests/data/input_postgres/create_buurten_table.sql.gz:/docker-entrypoint-initdb.d/create_buurten_table.sql.gz"
      - "../tests/data/input_postgres/insert_buurten.sql.gz:/docker-entrypoint-initdb.d/insert_buurten.sql.gz"
      - "../tests/data/input_postgres/create_3dbag_lod13.sql.gz:/docker-entrypoint-initdb.d/create_3dbag_lod13.sql.gz"
      - "../tests/data/input_postgres/create_insert_lod13.sql.gz:/docker-entrypoint-initdb.d/insert_3dbag_lod13.sql.gz"
